#!/bin/sh

build_type="$1"

if [ -z "${build_type}" ]
then
    echo "No build type!"
fi

YY_INSTALL_DIR="${HOME}/code/cpp/build"
YY_TP_DIR="${HOME}/code/tp"

echo "\nyy_test"
cd ../yy_test/build
make clean
rm -rf ./*
cmake --fresh -DCMAKE_INSTALL_PREFIX=${YY_INSTALL_DIR} -DYY_THIRD_PARTY_LIBRARY=${YY_TP_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=${build_type} ..
make all && make install || exit 1

echo "\nyy_tp_util"
cd ../../yy_tp_util/build
make clean
rm -rf ./*
cmake --fresh -DCMAKE_INSTALL_PREFIX=${YY_INSTALL_DIR} -DYY_THIRD_PARTY_LIBRARY=${YY_TP_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=${build_type} ..
make all && make install || exit 1

echo "\nyy_cpp"
cd ../../yy_cpp/build
make clean
rm -rf ./*
cmake --fresh -DCMAKE_INSTALL_PREFIX=${YY_INSTALL_DIR} -DYY_THIRD_PARTY_LIBRARY=${YY_TP_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=${build_type} ..
make all test && make install || exit 1

echo "\nyy_json"
cd ../../yy_json/build
make clean
rm -rf ./*
cmake --fresh -DCMAKE_INSTALL_PREFIX=${YY_INSTALL_DIR} -DYY_THIRD_PARTY_LIBRARY=${YY_TP_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=${build_type} ..
make all test && make install || exit 1

echo "\nyy_mqtt"
cd ../../yy_mqtt/build
make clean
rm -rf ./*
cmake --fresh -DCMAKE_INSTALL_PREFIX=${YY_INSTALL_DIR} -DYY_THIRD_PARTY_LIBRARY=${YY_TP_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=${build_type} ..
make all test && make install || exit 1

echo "\nyy_prometheus"
cd ../../yy_prometheus/build
make clean
rm -rf ./*
cmake --fresh -DCMAKE_INSTALL_PREFIX=${YY_INSTALL_DIR} -DYY_THIRD_PARTY_LIBRARY=${YY_TP_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=${build_type} ..
make all && make install || exit 1

echo "\nyy_web"
cd ../../yy_web/build
make clean
rm -rf ./*
cmake --fresh -DCMAKE_INSTALL_PREFIX=${YY_INSTALL_DIR} -DYY_THIRD_PARTY_LIBRARY=${YY_TP_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=${build_type} ..
make all && make install || exit 1

echo "\nyy_mqtt_bridge"
cd ../../yy_mqtt_bridge/build-dir
make clean
rm -rf ./*
cmake --fresh -DCMAKE_INSTALL_PREFIX=${YY_INSTALL_DIR} -DYY_THIRD_PARTY_LIBRARY=${YY_TP_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=${build_type} ..
make all
cd ../
