#!/bin/sh

build_type="$1"

if [ -z "${build_type}" ]
then
    echo "No build type!"
fi

YY_INSTALL_DIR="${HOME}/code/cpp/build"
YY_TP_DIR="${HOME}/code/tp"

echo "\nyy_test"
cd ../yy_test/build
#make tidy || exit 1

echo "\nyy_tp_util"
cd ../../yy_tp_util/build
make tidy-all

echo "\nyy_cpp"
cd ../../yy_cpp/build
make tidy-all

echo "\nyy_json"
cd ../../yy_json/build
make tidy-all

echo "\nyy_mqtt"
cd ../../yy_mqtt/build
make tidy-all

echo "\nyy_prometheus"
cd ../../yy_prometheus/build
make tidy-all

echo "\nyy_web"
cd ../../yy_web/build
make tidy-all

echo "\nyy_mqtt_bridge"
cd ../../yy_mqtt_bridge/build-dir
make tidy-all
cd ../
