#!/bin/sh

. ./build_config

build_type="$1"

if [ -z "${build_type}" ]
then
    echo "No build type!"
fi

YY_INSTALL_DIR="${HOME}/code/cpp/build"
YY_TP_DIR="${HOME}/code/tp"

echo "\nyy_test"
cd ../yy_test/build
#${YY_MAKE} tidy || exit 1

echo "\nyy_tp_util"
cd ../../yy_tp_util/build
${YY_MAKE} tidy-all

echo "\nyy_cpp"
cd ../../yy_cpp/build
${YY_MAKE} tidy-all

echo "\nyy_json"
cd ../../yy_json/build
${YY_MAKE} tidy-all

echo "\nyy_mqtt"
cd ../../yy_mqtt/build
${YY_MAKE} tidy-all

echo "\nyy_values"
cd ../../yy_values/build
${YY_MAKE} tidy-all || exit 1

echo "\nyy_prometheus"
cd ../../yy_prometheus/build
${YY_MAKE} tidy-all

echo "\nyy_web"
cd ../../yy_web/build
${YY_MAKE} tidy-all

echo "\nyy_mqtt_bridge"
cd ../../yy_mqtt_bridge/build-dir
${YY_MAKE} tidy-all
cd ../
