#!/bin/sh
YY_MAKE="nice $(which make) -j 4"

echo "yy_test: cleaning"
cd ../yy_test/build
${YY_MAKE} clean || exit 1

echo "yy_tp_util: cleaning"
cd ../../yy_tp_util/build
${YY_MAKE} clean || exit 1

echo "yy_cpp: cleaning"
cd ../../yy_cpp/build
${YY_MAKE} clean || exit 1

echo "yy_json: cleaning"
cd ../../yy_json/build
${YY_MAKE} clean || exit 1

echo "yy_maths: cleaning"
cd ../../yy_maths/build
${YY_MAKE} clean || exit 1

echo "yy_mqtt: cleaning"
cd ../../yy_mqtt/build
${YY_MAKE} clean || exit 1

echo "yy_prometheus: cleaning"
cd ../../yy_prometheus/build
${YY_MAKE} clean || exit 1

echo "yy_web: cleaning"
cd ../../yy_web/build
${YY_MAKE} clean || exit 1

echo "yy_mqtt_bridge: cleaning"
cd ../../yy_mqtt_bridge/build-dir
${YY_MAKE} clean || exit 1
cd ../
